runtime: nodejs12

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html
  secure: always
- url: /
  static_dir: public 

# - url: /(.*\..*)$
  # static_files: public/\1
  # upload: public/(.*\..*)$